# Generated by Django 4.1 on 2022-09-13 02:22

from django.db import migrations

#se crea la clase migration y algunos parametros dentro de la misma.
class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]
#se llevan a cabo el manejo de operaciones.
    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={
                "ordering": ["name"],
                "verbose_name": "Blog",
                "verbose_name_plural": "Blog Profiles",
            },
        ),
    ]
